// Even Fibonacci numbers - https://projecteuler.net/problem=2

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let fibonacci = [1, 2];
let evenNumbers = [2];

for(i = 1; i <= 10 ; i++) {
    const length = fibonacci.length;
    const newTerm = fibonacci[length - 1] + fibonacci[length - 2]
    if (i !== 0 || i !== 1 || i !== 2) {
        fibonacci.push(newTerm)
    }
    if (newTerm % 2 === 0) {
        evenNumbers.push(newTerm)
        console.log(newTerm)
    }
    
};

const sumEvenNumbers = evenNumbers.reduce( (acc, value) => acc + value);