// Pentagon numbers

/* 
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
*/

let pentagonal = [1];
let solution = null;

const toPentagonal = (number) => {
    return number * (3 * number - 1) / 2;
};

const verifyPentagonal = (number) => {
    if (number < 1 ) {
        return 0;
    }
    
    let numberB = (Math.sqrt(1 + 24 * number) + 1) / 6;

    if (numberB % 1 === 0) {
        return numberB;
    } else {
        return 0;
    }
}

const testsPentagonal = (a, b) => {
    if (verifyPentagonal(a) && verifyPentagonal(b) && verifyPentagonal(Math.abs(a-b))) {
        return verifyPentagonal(a + b);
    }
}

const findPentagonal = (number) => {
    for (i=0; i < pentagonal.length; i++){
        if (testsPentagonal(pentagonal[i], number)) {
            return [number, pentagonal[i]];
        }
    }

    return null;
}

while (solution === null) {
    let next = toPentagonal(pentagonal.length);
    solution = findPentagonal(next);
    pentagonal.push(next);
}

console.log('The value of D is: ' + Math.abs(solution[0] - solution[1]));